server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/orderdb
spring.datasource.username=postgres
spring.datasource.password=@13M25y1

eureka.client.service-url.defaultZone=http://localhost:8761/eureka